### ISSUE TITLE
In the generated RDF, articles year ends with ".0"

### ISSUE THREAD

**Issue by frmichel** [issa-project/issa-pipeline#1] opened 2022-04-28 08:49 UTC
Looks like the year is interpreted as a float instead of a int. Results in something like:
"2019.0"^^<http://www.w3.org/2001/XMLSchema#gYear>

**Comment by AnnaBobasheva** [comment] 2022-05-11 16:13
This was caused by one null value in the metadata.  Fixed by filling _n/a_ values of the _year_ column in the matadada tsv file.

**Comment by AnnaBobasheva** [comment] 2022-05-13 09:33
Another way to ensure the types of the columns imported into MongoDB would be to alter the header of the  metadata TSV file with included types into the header of the file. For example, for the column _year_ it should be _year.int32()_.  And include _--columnsHaveTypes_ option into _mongoimport_ command. 

Reference for the types can be found [here][(https://www.mongodb.com/docs/database-tools/mongoimport/#std-label-example-csv-import-types](https://www.mongodb.com/docs/database-tools/mongoimport/#std-option-mongoimport.--columnsHaveTypes). Examples can be found [here](https://www.mongodb.com/docs/database-tools/mongoimport/#std-label-example-csv-import-types)

Given that each column header has to be annotated with the type and prior fix of filling the null values to the only integer column, we forgo this step in the Agrovoc use case.

**Closed** 2022-05-13 09:34 UTC
